### PR TITLE
Allow to append ciphers to default set

### PR DESCRIPTION
**Pull request by languitar**
Adds an option to append ciphers given via the environment variable to the pre-selected list of ciphers. This allows a fine-grained customization of the pre-selected ciphers without having to repeat all of them again.

### CODE REVIEW

**Comment by languitar** [comment]
Any interest in this?

**Comment by MarcelWaldvogel** [comment]
Thank you for the pull request. I have included it (with adaptation to the current changes and switching to static memory allocation). I have avoided dynamic memory allocation so far, as it might conflict with the main application.

**Comment by languitar** [comment]
Thanks!

**Comment by languitar** [comment]
I just see that the README.md should also be updated with the changed documentation string.

**Pull request merged**
